### ISSUE TITLE
docker-compose is not working local development

### ISSUE THREAD

**Issue by kiliczsh** [enderahmetyurt/podiscover#121]
Previously I had configured .env file locally and just running `docker-compose up` and db:create & db:migrate then I could access to the application. I have created a branch for working version of docker-compose I implemented: [fix-docker](https://github.com/enderahmetyurt/podiscover/tree/fix-docker).

@enderahmetyurt can you try to use docker-compose locally. Otherwise people won't be able to have a easy onboarding for contribution.

**Comment by enderahmetyurt** [comment]
what's the difference in your working version branch than main?

**Comment by enderahmetyurt** [comment]
I tried and got this
![Screenshot 2023-05-17 at 21 31 05](https://github.com/enderahmetyurt/podiscover/assets/447588/e4f54543-6de1-419e-8fd7-375fba011a46)

**Comment by kiliczsh** [comment]
There are 3 services running, db, app and redis. For development I was stopping app and using `rails server` to work on it. 
Now I can't create docker image in the first place. I couldn't have time to dive into the problem.

**Comment by enderahmetyurt** [comment]
I am not good at docker things :/ but I will take care of it.
