### ISSUE TITLE
Log In with Spotify is not working

### ISSUE THREAD

**Issue by kiliczsh** [enderahmetyurt/podiscover#136]
When I try login on http://podiscover.me/ I get `INVALID_CLIENT: Invalid redirect URI`

Payload
client_id: a...b
redirect_uri: http://podiscover.me/users/auth/spotify/callback
response_type: code
scope: user-read-email user-library-read user-read-playback-position
state: 075...88e

@enderahmetyurt

**Comment by enderahmetyurt** [comment]
could you try http://www.podiscover.me/

**Comment by enderahmetyurt** [comment]
May I close it?

**Comment by kiliczsh** [comment]
You can add another callback url may be? It would be a chance to fix it

**Comment by enderahmetyurt** [comment]
I added `http://podiscover.me/users/auth/spotify/callback` let's see

**Comment by kiliczsh** [comment]
It seems to be fixed 🚀
