### ISSUE TITLE
css overlap problem 

### ISSUE THREAD

**Issue by kiliczsh** [enderahmetyurt/podiscover#138]
http://www.podiscover.me/podcasts/38/episodes/130806

<img width="624" alt="Screenshot 2023-06-07 at 22 34 07" src="https://github.com/enderahmetyurt/podiscover/assets/3473393/9fb3b75b-f2af-4fd0-9b5f-2da93b984d55">

See on spotify is overlapping with text. There is 2 more possible duplicate errors:
https://github.com/search?q=repo%3Aenderahmetyurt%2Fpodiscover+%22%3ESee+on+Spotify%3C%22&type=code

**Comment by Thallesmel** [comment]
Hey @kiliczsh I can try to solve it!

**Comment by kiliczsh** [comment]
Resolved by #182
