### ISSUE TITLE
Migration Problem 

### ISSUE THREAD

**Issue by kiliczsh** [enderahmetyurt/podiscover#148]
Whenever I run migration episode_segments is lost. Is there a possibility that migration does not exists?

<img width="685" alt="Screenshot 2023-06-17 at 21 34 34" src="https://github.com/enderahmetyurt/podiscover/assets/3473393/afaaddd6-dd2d-4a5b-bd47-e0c7f6857dd6">

**Comment by enderahmetyurt** [comment]
Ups! :/ It's my bad. I tried something in my local. It wouldn't have been here. I guess I commited it accidently. I will remove it. Thanks.
