### ISSUE TITLE
Add new social channels

### ISSUE THREAD

**Issue by enderahmetyurt** [enderahmetyurt/podiscover#176]
Adding instagram and medium blog accounts' links to the footer.

instagram: https://instagram.com/podiscoverme
blog: blog.podiscover.me

**Comment by haiderashfaq** [comment]
readme footer?

**Comment by enderahmetyurt** [comment]
> readme footer?

It would be, but we need to add them application footer

**Comment by kiliczsh** [comment]
Resolved by #179
