### ISSUE TITLE
Set CI 

### ISSUE THREAD

**Issue by enderahmetyurt** [enderahmetyurt/podiscover#29]
We need to set continuous integration.

**Comment by kiliczsh** [comment]
@enderahmetyurt  if you have a test environment, I would work on setting up automatic deployment for test environment

**Comment by enderahmetyurt** [comment]
We don't have test environment. Yes you can work on it. Maybe we can create a simple CI for now since we don't have many tests now.

**Comment by kiliczsh** [comment]
Which platform is podiscover is hosted on?

**Comment by enderahmetyurt** [comment]
Heroku
