### ISSUE TITLE
Potential bug in FetchUserPodcasts job

### ISSUE THREAD

**Issue by umurgdk** [enderahmetyurt/podiscover#86]
Shouldn’t each iteration increment the offset by 50 (given the limit is 50) instead of 1?

https://github.com/enderahmetyurt/podiscover/blob/fbf0ec0523625bb0589496fd1ce0d6b6d1a79803/app/jobs/fetch_user_podcasts.rb#L16

**Comment by enderahmetyurt** [comment]
Thank you 🙏 you probably right. Would you like to fix it? :)

**Comment by enderahmetyurt** [comment]
https://github.com/enderahmetyurt/podiscover/commit/2341c83fb0350cb139a895059c1aae53c078444a
